on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@9fbc767707c286e568c92927bbf57d76b73e0892
      with:
        go-version: '1.14.x'
    - name: Install Vim
      uses: myitcvscratch/myfirstaction@7a7c90cd7adb9c4252bda1a2c9cbed36352703ed
