on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

name: Test
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            go_version: "go1.13.5"
            vim_flavor: "vim"
            vim_version: "v8.1.2056"
            vim_command: "vim"
          - os: ubuntu-latest
            go_version: "go1.13.6"
            vim_flavor: "vim"
            vim_version: "v8.1.2056"
            vim_command: "vim"
    runs-on: ${{ matrix.os }}
    env:
      GO_VERSION: ${{ matrix.go_version }}
      VIM_FLAVOR: ${{ matrix.vim_flavor }}
      VIM_VERSION: ${{ matrix.vim_version }}
      VIM_COMMAND: ${{ matrix.vim_command }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Dump env
      run: env
